version: "3.5"
services:
    doh:
        image: rekey/doh:tls
        restart: unless-stopped
        container_name: doh
        environment:
            - ssl=dns.ja
        volumes:
            - ./doh/data:/app/store
    adguard:
        image: rekey/adguard
        restart: unless-stopped
        container_name: adguard
        links:
            - doh:dns.ja
        depends_on:
            - doh
        volumes:
            - ./adguard/data:/opt/work/data
            - ./adguard/config:/opt/conf
            - ./doh/data:/opt/pem
        ports:
            - 80:80
            - 53:53/udp